services:
  author:
    image: tugboatqa/debian:10
    default: true
    expose: 4502
    
    commands:
      init:
        # Install Java SDK and Maven.
        - apt-get update && apt-get install -y openjdk-11-jdk maven
        
        # Create directory structure. license.properties is base64 encoded as a TB repos variable.
        - mkdir -p /opt/aem/author
        - echo "${LICENSE_PROPERTIES}" | base64 --decode > /opt/aem/author/license.properties
        - ln -snf ${TUGBOAT_ROOT} /opt/aem/code
        
        # Download AEM quickstart file and install
        - wget -O /opt/aem/author/aem-author-p4502.jar "${AEM_FILE_URL}"
        - cd /opt/aem/author && java -jar aem-author-p4502.jar -unpack
          
        # Configure the Adobe public profile.
        - cp -r ${TUGBOAT_ROOT}/.tugboat/resources/.m2 ~/m2
        - mvn help:effective-settings
        
        # Make a runit script to automatically run aem 
        - mkdir -p /etc/service/aem && touch /etc/service/aem/run
        - echo "#!/bin/sh -eu\nexec 2>&1\nexec CQ_PORT=4502 /opt/aem/author/crx-quickstart/bin/start" >> "/etc/service/aem/run"
        - chmod a+x /etc/service/aem/run
                
      start:
        # sv restart aem
        # Note: This command will take minutes to run on the first boot.
        # tail -f /opt/aem/author/crx-quickstart/logs/error.log to watch it.
        # CQ_PORT=4502 /opt/aem/author/crx-quickstart/bin/start
        # Update the host of the default replication agent from localhost to the publish service.
        # This will return a 404 because the system won't be fully booted and won't work.
        # curl -u admin:admin -F"sling:resourceType=cq/replication/components/agent" -F"transportUri=http://publish:4503/bin/receive?sling:authRequestLogin=1" http://localhost:4502/etc/replication/agents.author/publish/jcr:content
