services:
  debian:
    image: tugboatqa/debian:10
    default: true
    expose: 4502
    
    commands:
      init:
        # Install Java SDK, Maven and Node JS.
        - curl -sL https://deb.nodesource.com/setup_14.x | sh
        - apt-get install -y openjdk-11-jdk maven nodejs
        
        # Create directory structure.
        - mkdir -p /opt/aem/author
        # The license.properties file is base64 encoded and available as a Tugboat repository variable.
        - echo "${LICENSE_PROPERTIES}" | base64 --decode > /opt/aem/author/license.properties
        - ln -snf ${TUGBOAT_ROOT} /opt/aem/code
        
        # Clone Dropbox SDK repository and install it.
        - git clone https://github.com/dropbox/dropbox-sdk-js.gi /opt/dbcli
        - npm install --prefix /opt/dbcli
        - npm run binaries --prefix /opt/dbcli
        # mv /opt/boxcli/dist/cli-linux /usr/local/bin/box
        
        # Download AEM quickstart file and install
        # box files:download BOX_FILE_ID --destination=/opt/aem/author/aem-author-p4502.jar
        # cd /opt/aem/author && java -jar aem-author-p4502.jar -unpack && cd -
        # cp /opt/aem/author/aem-author-p4502.jar /opt/aem/publish/aem-publish-p4503.jar
        # cd /opt/aem/publish && java -jar aem-publish-p4503.jar -unpack && cd -

      build:
      start: